name: Publish Docker image (develop)

on:
  push:
    branches:
      - develop
  workflow_dispatch:


jobs:
  # see https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    if: github.repository == 'team-shahu/misskey'
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/misskey:latest \
          --tag ghcr.io/$GITHUB_ACTOR/misskey:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/misskey:latest
          docker push ghcr.io/$GITHUB_ACTOR/misskey:$(echo $GITHUB_SHA | head -c7)
