name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY_IMAGE: misskey/misskey
  TAGS: |
    type=edge
    type=ref,event=pr
    type=ref,event=branch
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=semver,pattern={{major}}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    if: github.repository == 'team-shahu/misskey'
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: ${{ env.TAGS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/${{ github.repository_owner }}/misskey:latest \
          --tag ghcr.io/${{ github.repository_owner }}/misskey:$${{ steps.meta.outputs.version }} \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/misskey:latest
          docker push ghcr.io/${{ github.repository_owner }}/misskey:$${{ steps.meta.outputs.version }}
